# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200513_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='mainPicture',
            field=models.FileField(null=True, upload_to='articleMainPic/', verbose_name='mainPicture'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Keywords'),
        ),
    ]
