# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-19 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200514_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
